
#ifndef SERIAL_DRIVER_IOCTL_H
#define SERIAL_DRIVER_IOCTL_H
#include <asm/ioctl.h>

#define SERIAL_DRIVER_IOC 'w'
#define SERIAL_DRIVER_SET_BAUD_RATE _IOW(SERIAL_DRIVER_IOC,0, int)
#define SERIAL_DRIVER_SET_DATA_SIZE _IOW(SERIAL_DRIVER_IOC,1, int)
#define SERIAL_DRIVER_SET_PARITY _IOW(SERIAL_DRIVER_IOC,2, int)
#define SERIAL_DRIVER_GET_BUF_SIZE _IOR(SERIAL_DRIVER_IOC,3, int)
#define SERIAL_DRIVER_SET_BUF_SIZE _IOW(SERIAL_DRIVER_IOC,4, int)

#endif
